# -*- coding: utf-8 -*-
"""Simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Ademola-Olorunnisola/TB-Estimator/blob/main/Simulation.ipynb
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp

"""#Parameter values

"""

N = 500000  #Total population


mu     = 8 / 1000 / 365  # Natural death rate per day
Lambda = mu * N  # Births Per day
delta  =  1 / 1000 / 365    # TB death rate per day

"""#Control Inputs"""

alpha = 1 / 365   #Vaccination rate ~ 1% of S per day
tau   = 1 / 30    # treatment rate per day

"""#Model Parameters

"""

beta =  0.010   # Transmission rate (every Infectious person infects 2 others on average)
sigma =  0.50   # Vaccination Inefficiency (50% effective)
gamma = 1 / 180 # Treatment completion (6 months treatment)
eps = 1 / 365   # Latency progression rate
phi = 0.03      # Exogenous reinfection rate (i.e R faces 43% infection risk)
rho = 0.21 * (1 / 180) # treatment failure (21% Failure)

R0 = (beta * eps) / ((eps + mu) * (tau + mu + delta))
print(f"R0 = {R0:.4f}")

"""#TB MODEL / ODE SYSTEM"""

def sveirt(t, x):
    S, V, E, I, T, R = x
    lam = beta * I / N
    dS = Lambda - lam*S     - alpha*S - mu*S
    dV = alpha*S - sigma*lam*V        - mu*V
    dE = lam*S + sigma*lam*V + (phi*R*I) / N - (eps + mu)*E
    dI = eps*E + rho*T      - (tau + mu + delta)*I
    dT = tau*I              - (gamma + rho + mu)*T
    dR = gamma*T            - mu*R - (phi*R*I) / N
    return [dS, dV, dE, dI, dT, dR]

"""#Initial conditions"""

I0  = 0.05 * N
V0  = 0.08 * N
E0  = 0.08 * N
T0  = 0.06 * N
R0  = 0.01 * N
S0  = N - V0 - E0 - I0 - T0 - R0

(S0 + V0 + E0 + I0 + T0 + R0)

"""#SOlve ODE"""

t_end = 365
t_eval = np.linspace(0, t_end, 1000)

x0     = [S0, V0, E0, I0, T0, R0]

sol = solve_ivp(
    sveirt,
    (0, t_end),
    x0,
    t_eval=t_eval,
    method='RK45',
    rtol=1e-8,
    atol=1e-10)

t            = sol.t
S, V, E, I, T, R = sol.y

"""#plot"""

compartment_plots = [
    (S, 'Susceptible (S)',  '#2196F3'),
    (V, 'Vaccinated (V)',   '#9C27B0'),
    (E, 'Exposed (E)',      '#FF9800'),
    (I, 'Infectious (I)',   '#F44336'),
    (T, 'On Treatment (T)','#009688'),
    (R, 'Recovered (R)',    '#4CAF50'),
]

for y, title, _ in compartment_plots:
    plt.figure(figsize=(6, 3))
    plt.plot(t, y)
    plt.title(title)
    plt.xlabel("Time")
    plt.ylabel("Population")
    plt.grid(True)
    plt.tight_layout()
    plt.show()